package com.ninelives.insurance.api.model;

import java.util.Date;

public class Coverage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.coverage_id
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private String coverageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.coverage_group
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private String coverageGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.name
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.recommendation
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private String recommendation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.description
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.has_beneficiary
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private String hasBeneficiary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.created_date
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.update_date
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.coverage.max_limit
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	private Long maxLimit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.coverage_id
	 * @return  the value of public.coverage.coverage_id
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public String getCoverageId() {
		return coverageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.coverage_id
	 * @param coverageId  the value for public.coverage.coverage_id
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setCoverageId(String coverageId) {
		this.coverageId = coverageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.coverage_group
	 * @return  the value of public.coverage.coverage_group
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public String getCoverageGroup() {
		return coverageGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.coverage_group
	 * @param coverageGroup  the value for public.coverage.coverage_group
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setCoverageGroup(String coverageGroup) {
		this.coverageGroup = coverageGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.name
	 * @return  the value of public.coverage.name
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.name
	 * @param name  the value for public.coverage.name
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.recommendation
	 * @return  the value of public.coverage.recommendation
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public String getRecommendation() {
		return recommendation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.recommendation
	 * @param recommendation  the value for public.coverage.recommendation
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setRecommendation(String recommendation) {
		this.recommendation = recommendation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.description
	 * @return  the value of public.coverage.description
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.description
	 * @param description  the value for public.coverage.description
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.has_beneficiary
	 * @return  the value of public.coverage.has_beneficiary
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public String getHasBeneficiary() {
		return hasBeneficiary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.has_beneficiary
	 * @param hasBeneficiary  the value for public.coverage.has_beneficiary
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setHasBeneficiary(String hasBeneficiary) {
		this.hasBeneficiary = hasBeneficiary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.created_date
	 * @return  the value of public.coverage.created_date
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.created_date
	 * @param createdDate  the value for public.coverage.created_date
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.update_date
	 * @return  the value of public.coverage.update_date
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.update_date
	 * @param updateDate  the value for public.coverage.update_date
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.coverage.max_limit
	 * @return  the value of public.coverage.max_limit
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public Long getMaxLimit() {
		return maxLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.coverage.max_limit
	 * @param maxLimit  the value for public.coverage.max_limit
	 * @mbg.generated  Wed Nov 08 15:58:56 ICT 2017
	 */
	public void setMaxLimit(Long maxLimit) {
		this.maxLimit = maxLimit;
	}
}