package com.ninelives.insurance.api.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.coverage_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private String coverageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.period_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private String periodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.name
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.premi
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private Integer premi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.status
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.created_date
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.update_date
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_id
     *
     * @return the value of public.product.product_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_id
     *
     * @param productId the value for public.product.product_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.coverage_id
     *
     * @return the value of public.product.coverage_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public String getCoverageId() {
        return coverageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.coverage_id
     *
     * @param coverageId the value for public.product.coverage_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setCoverageId(String coverageId) {
        this.coverageId = coverageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.period_id
     *
     * @return the value of public.product.period_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public String getPeriodId() {
        return periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.period_id
     *
     * @param periodId the value for public.product.period_id
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setPeriodId(String periodId) {
        this.periodId = periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.name
     *
     * @return the value of public.product.name
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.name
     *
     * @param name the value for public.product.name
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.premi
     *
     * @return the value of public.product.premi
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public Integer getPremi() {
        return premi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.premi
     *
     * @param premi the value for public.product.premi
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setPremi(Integer premi) {
        this.premi = premi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.status
     *
     * @return the value of public.product.status
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.status
     *
     * @param status the value for public.product.status
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.created_date
     *
     * @return the value of public.product.created_date
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.created_date
     *
     * @param createdDate the value for public.product.created_date
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.update_date
     *
     * @return the value of public.product.update_date
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.update_date
     *
     * @param updateDate the value for public.product.update_date
     *
     * @mbg.generated Wed Nov 08 14:20:50 ICT 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}